version: '3.3'

networks:
  mynet:
    driver: bridge

services:
  # 用了YAML是什么锚点和别名
  mysql:
    image: mariadb:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: cloud_computing
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    networks:
      - mynet
    volumes:
      - ./src:/var/www/html

  myredis:
    image: redis:latest
    container_name: myredis
    networks:
      - mynet

  myphp:
    build:
      context: ./src/php
      dockerfile: dockerfile
    container_name: myphp
    expose:
      - 9000
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - myredis
    networks:
      - mynet

  mynginx:
    image: nginx:latest
    container_name: mynginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
    depends_on:
      - myphp
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: MyDBRoot123
    depends_on:
      - mysql
    networks:
      - mynet
